name: CF7 Coding Standards

on: pull_request

jobs:
  phpcs:
    name: Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: 'WordPress'
          use_local_config: 'true'
          extra_args: '--report-json=./phpcs.json'
          excludes: '.github/'
      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()


